import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Product",
  description: "Generated by create next app",
};

export default function ProductLayout({
  children, // will be a page or nested layout
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      {/* Include shared UI here e.g. a header or sidebar */}
      <nav>
        <ul>
          <li>a</li>
          <li>a</li>
          <li>a</li>
        </ul>
      </nav>

      {children}
    </section>
  );
}
